artifacts_root: artifacts

Data_ingestion:
  dir: artifacts/Data_ingetion
  train_data: artifacts/Data_ingetion/train.csv
  test_data: artifacts/Data_ingetion/test.csv
  raw_data: artifacts/Data_ingetion/raw.csv

Data_Trnsformation:
  dir: artifacts/Data_transformation
  train_data: artifacts/Data_ingestion/train.csv
  test_data: artifacts/Data_ingestion/test.csv
  train_arr: artifacts/Data_transformation/train.npy
  test_arr: artifacts/Data_transformation/test.npy
  preprocess_obj: artifacts/Data_transformation/preprocess.pkl

Model_Train:
  dir: artifacts/model_train
  train_arr: artifacts/data_transformation/train.npy
  test_arr: artifacts/data_transformation/test.npy
  model: artifacts/model_train/model.pkl



Prediction_pipline:
  model: artifacts/model_train/model.pkl
  preprocess_obj: artifacts/data_transformation/preprocess.pkl
  prediction_output_dirname: Predictions
  prediction_file_name:  predicted_file.csv