artifacts_root: artifacts

Data_ingestion:
  dir: artifacts/Data_ingetion
  train_data: artifacts/Data_ingetion/train.csv
  test_data: artifacts/Data_ingetion/test.csv
  raw_data: artifacts/Data_ingetion/raw.csv

Data_Trnsformation:
  dir: artifacts/data_transformation
  train_data: artifacts/data_ingestion/train.csv
  test_data: artifacts/data_ingestion/test.csv
  train_arr: artifacts/data_transformation/train.npy
  test_arr: artifacts/data_transformation/test.npy
  preprocess_obj: artifacts/data_transformation/preprocess.pkl
  